add loggers

diff --git a/build-all b/build-all
--- a/build-all
+++ b/build-all
@@ -1,14 +1,7 @@
 #!/bin/bash
 
-function finish()
-{
-	local RETVAL=$?
-	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
-}
-
-trap finish EXIT
-
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
 
 export TZ="UTC"
 
@@ -20,7 +13,17 @@ ionice --class 3     --pid $$ > /dev/null
 
 shopt -s nullglob
 
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
+
+trap finish EXIT
+
 cd /var/named
+
+[ $# = 0 ] && exit 2
 
 mkdir --parents "$DNSSEC_KEY_DIR"
 mkdir --parents data
diff --git a/delete-old-keys b/delete-old-keys
--- a/delete-old-keys
+++ b/delete-old-keys
@@ -1,14 +1,25 @@
 #!/bin/bash
 
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
+
+export TZ="UTC"
 
 set -o errexit	# set -e
 set -o nounset	# set -u
 
-shopt -s nullglob
-
 renice --priority 19 --pid $$ > /dev/null
 ionice --class 3     --pid $$ > /dev/null
+
+shopt -s nullglob
+
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
+
+trap finish EXIT
 
 cd /var/named
 
@@ -36,7 +47,7 @@ for f in $FILES; do
 	fi
 done
 
-echo -e "\e[1;32mDelete old keys\e[0m"
+log_info "Delete old keys"
 
 if [ ${#SAFE[@]} -gt 0 ]; then
 	echo "Safe:"
@@ -53,9 +64,9 @@ if [ ${#IGNORE[@]} -gt 0 ]; then
 fi
 
 if [ ${#DELETE[@]} -gt 0 ]; then
-	echo -e "\e[1;33mDelete:[0m"
+	log_warning "Delete:"
 	for f in ${DELETE[@]}; do
-		echo -e "\t\e[1;33m$f[0m"
+		log_warning "\t$f"
 		rm --force "$f"
 	done
 fi
diff --git a/disable-dnssec b/disable-dnssec
--- a/disable-dnssec
+++ b/disable-dnssec
@@ -1,14 +1,9 @@
 #!/bin/bash
 
-function finish()
-{
-	local RETVAL=$?
-	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
-}
-
-trap finish EXIT
-
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
+
+export TZ="UTC"
 
 set -o errexit	# set -e
 set -o nounset	# set -u
@@ -18,11 +13,19 @@ ionice --class 3     --pid $$ > /dev/null
 
 shopt -s nullglob
 
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
+
+trap finish EXIT
+
 cd /var/named
 
 [ $# = 0 ] && exit 2
 
-echo -e "\e[1;32mDisable DNSSEC\e[0m"
+log_info "Disable DNSSEC"
 
 if [ $# = 1 -a "$1" = "all" ]; then
 	set -- $DNSSEC_DOMAINS
diff --git a/fix-perms b/fix-perms
--- a/fix-perms
+++ b/fix-perms
@@ -1,6 +1,9 @@
 #!/bin/bash
 
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
+
+export TZ="UTC"
 
 set -o errexit	# set -e
 set -o nounset	# set -u
@@ -10,7 +13,17 @@ ionice --class 3     --pid $$ > /dev/null
 
 shopt -s nullglob
 
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
+
+trap finish EXIT
+
 cd /var/named
+
+[ $# = 0 ] || exit 2
 
 chown --recursive root.named .
 [ -d data ] && chown --recursive named.named data
diff --git a/generate-root-certs b/generate-root-certs
--- a/generate-root-certs
+++ b/generate-root-certs
@@ -1,15 +1,10 @@
 #!/bin/bash
 
-function finish()
-{
-	local RETVAL=$?
-	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
-}
-
-trap finish EXIT
-
-PATH="/var/named/bin:/usr/bin:/usr/sbin"
 CERT_FILE="named.ca"
+PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
+
+export TZ="UTC"
 
 set -o errexit	# set -e
 set -o nounset	# set -u
@@ -19,13 +14,21 @@ ionice --class 3     --pid $$ > /dev/null
 
 shopt -s nullglob
 
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
+
+trap finish EXIT
+
 cd /var/named
 
 [ $# = 0 ] || exit 2
 
-echo -e "\e[1;32mGenerate Root Certificates\e[0m"
+log_info "aenerate Root Certificates"
 if [ -f "$CERT_FILE" ]; then
-	echo -e "\t\e[1;33malready exists\e[0m"
+	log_warning "\talready exists"
 	exit 0
 fi
 
diff --git a/generate-tlsa b/generate-tlsa
--- a/generate-tlsa
+++ b/generate-tlsa
@@ -1,15 +1,10 @@
 #!/bin/bash
 
-function finish()
-{
-	local RETVAL=$?
-	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
-}
-
-trap finish EXIT
-
-PATH="/var/named/bin:/usr/bin:/usr/sbin"
 SUFFIX="tlsa.inc"
+PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
+
+export TZ="UTC"
 
 set -o errexit	# set -e
 set -o nounset	# set -u
@@ -19,15 +14,23 @@ ionice --class 3     --pid $$ > /dev/null
 
 shopt -s nullglob
 
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
+
+trap finish EXIT
+
 cd /var/named
 
 [ $# = 0 ] && exit 2
 
-echo -e "\e[1;32mGenerate TLSA Records for Services\e[0m"
+log_info "Generate TLSA Records for Services"
 for ZONE in $@; do
 	FILE="$ZONE.$SUFFIX"
 	if [ -f "$FILE" ]; then
-		echo -e "\t\e[1;33m$ZONE already exists\e[0m"
+		log_warning "\t$ZONE already exists"
 		continue
 	fi
 
diff --git a/set-to-publish-date b/set-to-publish-date
--- a/set-to-publish-date
+++ b/set-to-publish-date
@@ -1,14 +1,9 @@
 #!/bin/bash
 
-function finish()
-{
-	local RETVAL=$?
-	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
-}
-
-trap finish EXIT
-
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
+
+export TZ="UTC"
 
 set -o errexit	# set -e
 set -o nounset	# set -u
@@ -18,13 +13,21 @@ ionice --class 3     --pid $$ > /dev/null
 
 shopt -s nullglob
 
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
+
+trap finish EXIT
+
 cd /var/named
 
 if [ $# = 0 ]; then
 	set -- $DNSSEC_KEY_DIR/*.{key,private}
 fi
 
-echo -e "\e[1;32mSet to Publish Date\e[0m"
+log_info "Set to Publish Date"
 for f in "$@"; do
 	FILE_DATE=$(awk '/Publish/{ print $3 ? $3 : $2 }' $f)
 	if [ -z "$FILE_DATE" ]; then
diff --git a/show-keys b/show-keys
--- a/show-keys
+++ b/show-keys
@@ -1,14 +1,9 @@
 #!/bin/bash
 
-function finish()
-{
-	local RETVAL=$?
-	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
-}
-
-trap finish EXIT
-
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
+
+export TZ="UTC"
 
 set -o errexit	# set -e
 set -o nounset	# set -u
@@ -17,6 +12,14 @@ renice --priority 19 --pid $$ > /dev/null
 ionice --class 3     --pid $$ > /dev/null
 
 shopt -s nullglob
+
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
+
+trap finish EXIT
 
 cd /var/named
 
@@ -33,7 +36,7 @@ fi
 [ ${#FILES[@]} = 0 ] && exit 0
 
 for type in "key-signing" "zone-signing"; do
-	echo -e "\e[1;32m$type keys\e[0m"
+	log_info "$type keys"
 	ls -1 --sort=time --reverse "$DNSSEC_KEY_DIR"/*.key | while read x; do
 		grep --quiet $type "$x" || continue
 		echo $x
diff --git a/show-signed b/show-signed
--- a/show-signed
+++ b/show-signed
@@ -1,16 +1,25 @@
 #!/bin/bash
 
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
 
 export TZ="UTC"
 
 set -o errexit	# set -e
 set -o nounset	# set -u
 
-shopt -s nullglob
-
 renice --priority 19 --pid $$ > /dev/null
 ionice --class 3     --pid $$ > /dev/null
+
+shopt -s nullglob
+
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
+
+trap finish EXIT
 
 cd /var/named
 
@@ -19,7 +28,7 @@ for i in *.db.signed; do
 	SERIAL=${SERIAL:0:10}
 	ZONE=${i%.db.signed}
 	RECORDS=$(grep -cwh "RRSIG" "$i")
-	echo -e "\e[1;32mSigned zone: $ZONE\e[0m"
+	log_info "Signed zone: $ZONE"
 	echo -e "\tSerial:  $SERIAL"
 	echo -e "\tRecords: $RECORDS"
 	echo
diff --git a/sign-zone b/sign-zone
--- a/sign-zone
+++ b/sign-zone
@@ -1,14 +1,9 @@
 #!/bin/bash
 
-function finish()
-{
-	local RETVAL=$?
-	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
-}
-
-trap finish EXIT
-
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
+
+export TZ="UTC"
 
 set -o errexit	# set -e
 set -o nounset	# set -u
@@ -17,6 +12,14 @@ renice --priority 19 --pid $$ > /dev/null
 ionice --class 3     --pid $$ > /dev/null
 
 shopt -s nullglob
+
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
+
+trap finish EXIT
 
 cd /var/named
 
@@ -37,7 +40,7 @@ SALT=${SALT:0:16}
 SALT=${SALT^^}
 
 # Sign the zone, and write it out to a file named zone.signed
-echo -e "\e[1;32mSign zone $ZONE\e[0m (Salt: $SALT)"
+log_info "Sign zone $ZONE (Salt: $SALT)"
 dnssec-signzone -s "$START" -e "$END" -3 $SALT -S -o $ZONE -K "$DNSSEC_KEY_DIR" $ZONE.db
 mv dsset-$ZONE. "$DNSSEC_KEY_DIR"
 
diff --git a/update-serials b/update-serials
--- a/update-serials
+++ b/update-serials
@@ -1,14 +1,9 @@
 #!/bin/bash
 
-function finish()
-{
-	local RETVAL=$?
-	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
-}
-
-trap finish EXIT
-
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
+source log.sh
+
+export TZ="UTC"
 
 set -o errexit	# set -e
 set -o nounset	# set -u
@@ -18,7 +13,11 @@ ionice --class 3     --pid $$ > /dev/null
 
 shopt -s nullglob
 
-cd /var/named
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
+}
 
 function usage()
 {
@@ -26,6 +25,10 @@ function usage()
 	exit 1
 }
 
+
+cd /var/named
+
+trap finish EXIT
 
 if [ $# = 0 ]; then
 	FILE_LIST=(*.db)
@@ -70,7 +73,7 @@ done
 
 : $((SERIAL++))
 
-echo -e "\e[1;32mUpdate zone file serial numbers\e[0m"
+log_info "Update zone file serial numbers"
 for FILE in ${FILE_LIST[@]}; do
 	ZONE="${FILE%.db}"
 	sed -i "s/\<[0-9]\{10\}\>/$SERIAL/" $FILE
