check more retvals

diff --git a/generate-zsk b/generate-zsk
--- a/generate-zsk
+++ b/generate-zsk
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
+}
+
+trap finish EXIT
+
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
 
 set -o errexit	# set -e
@@ -8,13 +16,15 @@ set -o nounset	# set -u
 renice --priority 19 --pid $$ > /dev/null
 ionice --class 3     --pid $$ > /dev/null
 
+shopt -s nullglob
+
 cd /var/named
 
 echo -e "\e[1;32mGenerate Zone-Signing Key\e[0m"
 
 if [ ! $# = 1 -a ! $# = 3 ]; then
 	echo "Usage: ${0##*/} ZONE [YEAR MONTH]"
-	exit 1
+	exit 2
 fi
 
 ZONE="$1"
@@ -38,4 +48,6 @@ D="$(date "+%Y%m%d" --date "$YEAR-$MONTH-$DAY + $VALID + 2 days")$TIME"
 mkdir --parents "$DNSSEC_KEY_DIR"
 
 dnssec-keygen -a NSEC3RSASHA1 -n ZONE -K "$DNSSEC_KEY_DIR" -b 2048 -P $P -A $A -I $I -D $D $ZONE
+
+exit 0
 
diff --git a/sign-zone b/sign-zone
--- a/sign-zone
+++ b/sign-zone
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+function finish()
+{
+	local RETVAL=$?
+	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
+}
+
+trap finish EXIT
+
 PATH="/var/named/bin:/usr/bin:/usr/sbin"
 
 set -o errexit	# set -e
@@ -8,26 +16,19 @@ set -o nounset	# set -u
 renice --priority 19 --pid $$ > /dev/null
 ionice --class 3     --pid $$ > /dev/null
 
+shopt -s nullglob
+
 cd /var/named
 
 if [ $# != 1 -a $# != 2 ]; then
 	echo "Usage: ${0##*/} ZONE [start]"
-	exit 1
+	exit 2
 fi
-
-# for i; do echo ARG: $i; done
 
 ZONE=$1
 START=${2:-$(date "+%Y%m%d%H%M%S")}
 S2="${START:0:4}-${START:4:2}-${START:6:2} ${START:8:2}:${START:10:2}:${START:12:2}"
-# echo S2 = $S2
 END=$(date "+%Y%m%d%H%M%S" -d "$S2 + 2 days")
-
-# S2="${START:0:4}-${START:4:2}-${START:6:2} ${START:8:2}:${START:10:2}:${START:12:2}"
-# echo -n "Start: "; date -d "$S2"
-# S2="${END:0:4}-${END:4:2}-${END:6:2} ${END:8:2}:${END:10:2}:${END:12:2}"
-# echo -n "End:   "; date -d "$S2"
-# exit
 
 mkdir --parents "$DNSSEC_KEY_DIR"
 
